### ISSUE TITLE
checkDeviceIsClaimed causing crash

### ISSUE THREAD

**Issue by iain-reid** [spark/spark-setup-ios#25]
I'm having problems with the setup controller.
It crashes my app with the following error, every time: 

 **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SparkDevice objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1915b9a0'

at this line:

![image](https://cloud.githubusercontent.com/assets/1871804/7912104/5035ec74-085c-11e5-88b5-c14827de0fb8.png)

After the crash, I can login to the Particle Build portal and the device is shown, and the Cyan light on board is pulsing and connected - but obviously the crash is a problem.

I've reset the Photon (factory,Wifi) and also cleared it's ownership in the web portal and the Particle iOS app. Same error.

Any help on this issue would be appreciated! I'm running the app on iOS 8.2.

**Comment by idokleinman** [comment]
is this still an issue?

**Comment by iain-reid** [comment]
Hi, I'm not sure if it's still an issue - it's been a while since we worked on this project, and I don't have the kit to hand. Safe to close it i'd say :-)

**Comment by KillerGasy** [comment]
I getting this issue also

**Comment by idokleinman** [comment]
@KillerGasy This has been fixed.. What library pod version you are using?
