### ISSUE TITLE
False positive: setup "success" despite disconnected Photon

### ISSUE THREAD

**Issue by pomplesiegel** [spark/spark-setup-ios#28]
In some cases (varying/inconsistent WiFi reception/availability), we're seeing a fully "successful" setup procedure via the iOS app, despite that the Photon is still flashing green, looking for a connection. This occurs with both the iOS app "Particle," as well as our custom app, which uses the same SDK. This occurs both within iOS 8 and iOS9. 
Every step passes, including "Check for internet connectivity" and "verify device ownership"    

![img_0152](https://cloud.githubusercontent.com/assets/1450352/9968757/3c44bc06-5e18-11e5-8d6c-6b057982f490.PNG)

Can you reproduce this by repeatedly setting up a Photon under possibly varying WiFi conditions? 

In the past we have seen issues with both Core + Photon wherein `particle list` or the dashboard contain out-of-date state regarding whether a device is actually connected to the cloud. Might these issues be related?

**Comment by pomplesiegel** [comment]
@idokleinman, any thoughts on this? We want to make sure that by the time we integrate the WiFi setup SDK into our app, the program will accurately reflect the user's connectivity. Currently the app sometimes shows a false positive (shown above) even through the Photon never successfully reached the cloud.

**Comment by karlhenricksen** [comment]
I see this same thing, but it seems to me the issue is more generic, and after the first checkpoint "Configure Device Wi-Fi Credentials", the rest are non-functional checks - is this the case?

The easiest way to see this in action is to supply an incorrect wifi password - it sends the credentials successfully, but then all of the other checks pass and reports "Setup completed successfully".  Meanwhile, the Photon has gone to steady green LED, followed by blinking blue listening mode - definitely not a success on any of those checks (no wifi connect, no internet, no cloud connect etc). 

@m-mcgowan is there any outlook on this working?  Would be great to have a way to get customers some feedback if they misspell a password on setup, rather than a misleading success screen.

**Comment by idokleinman** [comment]
@pomplesiegel does this happen only on a device that was setup successfully before? I indeed suspect that the cloud is reporting this device to be online & owned by the app's currently logged in user

@karlhenricksen basically the "verify device ownership" step polls the cloud device list API to check if the device appears under the user account & online. Rest of the steps - the iOS device is recovering its internet connectivity after being connected to the Photon's SSID network

**Comment by pomplesiegel** [comment]
@idokleinman, thanks for the response! We just tried unclaiming a photon and setting it up from scratch (unclaimed + no WiFi creds + system fw 0.4.6) using the Particle app. 

On the first try of WiFi setup the photon SOS'd due to [this](https://github.com/spark/firmware/issues/663) bug (unrelated, so not worried about that), causing the Photon to be offline. However, the app still posted a checkmark for all 5 checks, thinking that the Photon was online, while it was clearly not connected to the cloud!

So it appears this is an issue for Photons new to the cloud as well.

@dmiddlecamp & @m-mcgowan , Perhaps is it time to take a larger look at device online/offline reporting w/ the cloud, as that issue seems to bring tentacles into multiple areas?

On our app, we no longer rely on Particle's `device.connected`, as it became clear this often does not represent the current online/offline state of a Core or Photon. Many times a Photon or Core will be breathing cyan, happily responding to `get`s and `call`s, but `device.connected` and `particle list` will show it as offline. Indeed, when visiting Particle HQ we were instructed not to rely on `device.connected` as an indication of whether a device is online.

**Comment by pomplesiegel** [comment]
@idokleinman, any plan for how to fix this? It's been more than a month without any update. 

When "Particle Setup" is integrated into our app, the customer needs to know whether their ioT device has successfully connected. Currently, there is no accurate confirmation regarding a successful vs unsuccessful WiFi setup, which will lead to serious customer confusion.

**Comment by kneuron** [comment]
Just want to add my two cents - we're seeing very similar behavior in the spark-setup-android, and it's a problem for us as well.

**Comment by idokleinman** [comment]
@pomplesiegel sorry for the delayed responses, we've been hard at work on Electron related development and new iOS/Android app releases has been postponed. So to clarify on the Soft-AP setup flow inner workings - once the Photon drops connection with the mobile device we have no way to know at what state it is - meaning we cannot really know if you supplied wrong wifi credentials. The last checkpoint only checks (polls) that the Photon appears in the current user's device list (means that it is claimed) - so if it has been setup before, it might appear in that list which will cause the setup to report success. We should consider adding a check that the device is really online. I did encounter some invalid reporting of online/offline state of devices by the cloud in the past  however we did improve on the online/offline reporting in latest Photon firmware (0.4.6+) - are you using the latest firmware?

**Comment by zsup** [comment]
Adding a check that the device is in fact online definitely seems like a good step, and will provide a clear user flow for online (report success) vs. offline but claimed devices (report failure to connect, let the customer keep trying or re-start the process). Also we should add this for Android if it's the same on both systems

**Comment by pomplesiegel** [comment]
@idokleinman, thanks for the response. Totally understand you're juggling many projects at the moment. Yes, we are using 0.4.7, but this reporting has remained constant since about 0.4.5. 

@zsup, Totally. Online/offline checks would allow much greater accuracy regarding whether the WiFi cred setup has been successful or not. In the end, all that the customer knows about is whether their device has successfully connected. An error checking mechanism to redirect them back to the beginning would be a major improvement. Would this be integrated into the API used by customers' apps as well?

The only thing i'd like to warn about is that among our fleet we have often seen `device.connected`  consistently return inaccurate state regarding a Photon or Core's online/offline status. This API call is consistent with results using `particle list`. Often devices which are currently connected will be listed as "offline" or vice versa. For that reason we were instructed by Particle not to rely on `device.connected` as an indication of whether a device is online.

**Comment by zsup** [comment]
Sounds like there are two issues here, each of which should be addressed separately:

1) Making sure that the app properly manages the case where the device is claimed but offline @idokleinman

2) Making sure that the API properly reports whether devices are online/offline, and that any temporary discrepancies (like when a device disconnects but doesn't close the TCP socket, which means that it will report online until it misses a ping from the cloud) are clearly documented in the API docs @dmiddlecamp 

Does that sound right?

**Comment by pomplesiegel** [comment]
Sounds totally right! Thank you

**Comment by idokleinman** [comment]
:+1:

**Comment by idokleinman** [comment]
We plan to fix those issues in the device setup library code and post a new update to Tinker app in the coming 3 weeks.

**Comment by pomplesiegel** [comment]
Great! By the "Tinker app" do you mean the "Particle" app available in the iOS store?

**Comment by idokleinman** [comment]
@pomplesiegel yes.. again sorry for delays. Hard at work on Electron stuff.
Hopefully next sprint we'll add a warning if setup succeeds but Photon is offline

**Comment by pomplesiegel** [comment]
Great, looking forward to it, as this will be in customers' hands in not too long. Thanks!
