### ISSUE TITLE
Launching on non-root view controllers crashes the phone.

### ISSUE THREAD

**Issue by crenwick** [spark/spark-setup-ios#36]
Launching the spark setup via:

``` swift
  @IBAction func beginSetupTouched(sender: AnyObject) {
    if let vc = SparkSetupMainController() {
      vc.delegate = self
      self.presentViewController(vc, animated: true, completion: nil)
    }
  }
```

works fine on the root controller, but when I try to make this action happen on a nested view controller (but still the controller in view), it not only crashes the app but causes the entire phone to restart--losing connection with xcode and making it difficult to debug.

So far, it seems to get to get all the way through the [viewDidLoad method](https://github.com/spark/spark-setup-ios/blob/master/Classes/User/SparkSetupMainController.m#L89-L120) before crashing.

**Comment by crenwick** [comment]
Inside that nested view controller, I can present the SparkSetup on the root controller like so:

``` swift
if let vc = SparkSetupMainController() {
  vc.delegate = self

  UIApplication.sharedApplication().keyWindow!.rootViewController?.dismissViewControllerAnimated(false, completion: { () -> Void in
    UIApplication.sharedApplication().keyWindow!.rootViewController?.presentViewController(vc, animated: true, completion: nil)
  })
}
```

This is obviously not the desired behavior I want, as now I need to handle the strange animation of dismissing and presenting two view controllers at the same time, and I also have to handle the logic to bring back the desired (nested) view controller when the SparkSetup completes.

I'm sure this will also cause issues when the SparkSetup dismisses, as the nested view controller is the `SparkSetupMainControllerDelegate` and not the root view controller.

**Comment by idokleinman** [comment]
What do you mean works well only on root viewcontroller?
You can take the Particle app (Tinker) as an example - it pops up a Setup 'wizard' modal flow which is not on the root VC without any issues. Maybe take a look on that repo as a reference.
https://github.com/spark/photon-tinker-ios

**Comment by crenwick** [comment]
Hmmm. I cloned [this fork of the example app](https://github.com/Andrewpk/spark-setup-ios-example/tree/7bd784b693042a38de439ba0b5ca1e220272d79c) and was able to get view controllers working without the crashing bug.

I'll try to dig around more and figure out why this is happening with my app.

**Comment by idokleinman** [comment]
Great, happy to hear. I'm closing this issue for now, feel free to re-open if necessary or post in our community website if more help is needed
https://community.particle.io/c/mobile
