### ISSUE TITLE
Build-Errors using Swift Pods

### ISSUE THREAD

**Issue by henrik-d** [spark/spark-setup-ios#39]
I have problems using SparkSetup with CocoaPods in Swift.

These were my steps:
1) Create a new Swift-Project in Xcode
2) Create a Podfile and install

```
platform :ios, '8.0'
use_frameworks!

target 'ParticleTest' do
    pod 'SparkSetup'
end
```

3) `import SparkSetup` in ViewController.swift 

I get these errors:
![bildschirmfoto 2016-01-20 um 10 06 31](https://cloud.githubusercontent.com/assets/6033679/12444172/855a450e-bf5d-11e5-9569-ab4560678dbf.png)

**Comment by idokleinman** [comment]
Seems like you did not create bridging headers.

See here:
http://swiftalicio.us/2014/11/using-cocoapods-from-swift/
http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/

**Comment by henrik-d** [comment]
Thanks for the quick reply.

I can't use bridging headers, since I use `use_frameworks!` in my Podfile (which I have to, because I also want to use swift-only-libraries)

**Comment by idokleinman** [comment]
I think you can, read here:
http://stackoverflow.com/questions/29905271/unable-to-use-both-swift-and-obj-c-libs-with-cocoapods

**Comment by henrik-d** [comment]
Thanks, thats working for me. Didn't know that having both is possible!

**Comment by ghost** [comment]
Hi there, I was running into the same issue, and I followed the link to use both swift and obj-c using search paths. The `file not found` error went away, but the `file not found with <angled>` error is still occurring. This only happens when I try to build the project with a device. It works fine in the simulator.

**Comment by idokleinman** [comment]
Is your project in swift? 
Do you have (other) swift dependencies in your project? 
Do you use `use_frameworks!` in Podfile?

**Comment by asanchezdelc** [comment]
@idokleinman yes to all.

In the mean time, I got it working by just modifying the `SparkSetup.h` includes to use quotes.

**Comment by idokleinman** [comment]
I am glad to hear. Which includes you had to change? You are welcome to submit a PR btw.

**Comment by asanchezdelc** [comment]
On `SparkSetup.h` I changed the <angled> imports to

```
#import "SparkSetupCustomization.h"
#import "SparkSetupMainController.h"
```

**Comment by henrik-d** [comment]
These changes where necessary for me as well.

**Comment by idokleinman** [comment]
I'll fix it in the next update of the device setup lib.
Thanks!
