### ISSUE TITLE
'isAuthenticated' not found

### ISSUE THREAD

**Issue by woxaixni** [spark/spark-setup-ios#43]
whenever it have "if ([SparkCloud sharedInstance].isAuthenticated)" throw me an error
**error**
/Users/VICE/Downloads/photon-tinker-ios-master/Pods/SparkSetup/Classes/UI/SparkGetReadyViewController.m:66:37: Property 'isAuthenticated' not found on object of type 'SparkCloud *'

also on
SparkDiscoverDeviceViewController.m#430 [SparkCloud sharedInstance].isAuthenticated
SparkSetupMainController.m#96 [SparkCloud sharedInstance].isAuthenticated 
sorry if I'm newbie. thanks
running SDK ios9.2

**Comment by idokleinman** [comment]
This is WIP on the spark-sdk-ios repo, will be released soon along with documentation. be sure to use latest official release and not tip of the master branch.
