### ISSUE TITLE
Could not load the "xxxxxxxxx.png" image referenced from a nib in the bundle with identifier "(null)"

### ISSUE THREAD

**Issue by iain-reid** [spark/spark-setup-ios#46]
I've added pod 'SparkSetup' and the libraries appear to have been added correctly - the setup view controller presents and functions correctly.

_However_ it is missing all of the imagery/loaders etc. I get warnings in the log window - "Could not load the "xxxxxxxxx.png" image referenced from a nib in the bundle with identifier "(null)" for every image.

Looking into the pod folder, the **setup.storyboard** views look empty (nothing being drawn) however all of the UI/connections to images etc. appear correct (see image)

![setup_storyboard_ _edited](https://cloud.githubusercontent.com/assets/1871804/15859242/30f6ae22-2cbc-11e6-96c0-7d7276fcd972.jpg)

The setup.xcassets folder looks correct - the images are all there.

I may be overlooking something simple - any help would be much appreciated :-)

**Comment by idokleinman** [comment]
which pod version did you use?
this issue was fixed on 0.4.1 
https://github.com/spark/spark-setup-ios/blob/master/CHANGELOG.md#041-2016-5-19

**Comment by iain-reid** [comment]
I've updated Cocoapods to 1.0.0 and it seems to work now - been resisting as Parse SDK seems to have an issue with 1.0.0... round and round we go :-p

Thanks for the advice though!

**Comment by williamhqs** [comment]
How did you solve this issue? I updated to Cocoapods 1.0.1 too. Still got the same issue. Thank you! @DeepLight @idokleinman 

```
- Spark-SDK, 0.4.1
- SparkSetup, 0.5.0
```

**Comment by iain-reid** [comment]
Hey @williamhqs - not sure if this makes any difference, but I've left use_frameworks commented out in the podfile, and I only include SparkSetup (as I think spark-SDK is pulled in anyway)

**Comment by williamhqs** [comment]
@deeplightco  Thank you. I can't comment out `Spark-SDK`, you are right. But i can't commented out `use_frameworks` because i use swift library....
@idokleinman Any help thanks!
