### ISSUE TITLE
SparkSession.h file not found

### ISSUE THREAD

**Issue by williamhqs** [spark/spark-setup-ios#47]
As the title described, after i run `pod install` i got this error. My pod file only has  `pod 'SparkSetup'`

**Comment by idokleinman** [comment]
checking...

**Comment by williamhqs** [comment]
I comment all run pod install and uncomment all run pod install, works.

**Comment by idokleinman** [comment]
not sure I understood the solution, can you explain?

**Comment by williamhqs** [comment]
Comment all like `// pod 'xxxx`, then run `pod install`. Something like reinstall not clear. But not shouldn't be update i think. Then install it again by `pod install`
