### ISSUE TITLE
'Couldn't add the Keychain Item.'

### ISSUE THREAD

**Issue by williamhqs** [spark/spark-setup-ios#51]
I am working on two-legged auth part, after get the access_token from my server, i try to inject session:

`SparkCloud.sharedInstance().injectSessionAccessToken(dic["access_token"])`

got error:
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't add the Keychain Item.'
`

And should be this line issue.

```
KeychainItemWrapper *keychainTokenItem = [[KeychainItemWrapper alloc] initWithIdentifier:kSparkSessionKeychainEntry accessGroup:nil];
    [keychainTokenItem setObject:keychainData forKey:(__bridge id)(kSecValueData)];
```

Any help?

**Comment by williamhqs** [comment]
Fixed:
http://stackoverflow.com/questions/39614125/keychainitemwrapper-couldnt-add-the-keychain-item

**Comment by idokleinman** [comment]
Lovely - thanks for sharing. I think I'll have to add this piece of instruction to deploying apps with Particle SDK...

**Comment by williamhqs** [comment]
hi @idokleinman Sorry it's not Particle SDK issue. No need to add into instruction. My bad!

I update my apple account expired before i updated to Xcode 8. So i removed my account and re-login it works for my device now. But not simulator. 

Thank you!
